// Nội dung mặc định của trang chủ = giá trị gốc trong database/V4__home_and_payment_settings.sql.
// Dùng khi backend chưa chạy; Admin sửa nội dung thật ở Cài đặt hệ thống > Trang chủ.
export const DEFAULT_HOME = {
  "home.brand.name": "Gạch Coffee",
  "home.brand.tagline": "Mộc mạc như viên gạch, đậm đà như ly cà phê phin Việt.",
  "home.brand.logo": "",
  "home.brand.vn_logo": "",
  "home.hero1.image": "",
  "home.hero1.title": "Cà phê phin, rang mộc mỗi tuần",
  "home.hero1.subtitle": "Robusta Buôn Ma Thuột và Arabica Cầu Đất, pha chậm để giữ trọn vị đậm và hậu ngọt.",
  "home.hero2.image": "",
  "home.hero2.title": "Trà trái cây cho ngày nắng",
  "home.hero2.subtitle": "Trà đào cam sả, trà vải hoa hồng: thanh mát, ít ngọt, uống mãi không ngán.",
  "home.hero3.image": "",
  "home.hero3.title": "Sắp có đặt hàng online",
  "home.hero3.subtitle": "Chọn món trên web, trả bằng QR hoặc khi nhận hàng. Nhân viên quán giao tận nơi.",
  "home.feature1.image": "",
  "home.feature1.title": "Cà phê",
  "home.feature1.desc": "Từ ly phin sữa đá quen thuộc đến bạc xỉu, cold brew. Hạt được rang tại quán và xay ngay trước khi pha.",
  "home.feature2.image": "",
  "home.feature2.title": "Trà",
  "home.feature2.desc": "Trà ủ lạnh kết hợp trái cây theo mùa. Vị thanh, thơm tự nhiên, không dùng hương liệu.",
  "home.feature3.image": "",
  "home.feature3.title": "Đá xay và bánh",
  "home.feature3.desc": "Matcha, cookie đá xay cùng bánh nướng mỗi sáng cho buổi chiều thong thả.",
  "home.origin.image": "",
  "home.origin.title": "Câu chuyện của Gạch",
  "home.origin.content": "Gạch Coffee bắt đầu từ một căn nhà nhỏ lát gạch đỏ, nơi nhóm bạn trẻ yêu cà phê Việt rủ nhau rang những mẻ hạt đầu tiên.\nChúng tôi chọn tên Gạch vì muốn quán mộc mạc, bền bỉ và gần gũi như chính những viên gạch ấy: mỗi ly đều được làm chậm rãi và tử tế.",
  "home.services.heading": "Phục vụ theo cách bạn muốn",
  "home.service1.title": "Uống tại quán",
  "home.service1.desc": "Không gian gạch mộc, wifi mạnh. Quét mã QR trên bàn để gọi món, không cần chờ.",
  "home.service2.title": "Mang đi",
  "home.service2.desc": "Gọi món tại quầy, nhận đồ uống sau vài phút. Tích điểm bằng số điện thoại.",
  "home.service3.title": "Giao tận nơi",
  "home.service3.desc": "Đặt online, trả bằng QR hoặc khi nhận hàng. Đang hoàn thiện, sắp ra mắt.",
  "home.store.title": "Ghé quán",
  "home.store.address": "",
  "home.store.hours": "7:00 – 22:00, tất cả các ngày",
  "home.store.image": "",
  "home.contact.title": "Cần hỗ trợ? Gọi hoặc nhắn cho quán",
  "home.contact.hotline": "",
  "home.contact.email": "",
  "home.contact.facebook": "",
}

// Các mục trong menu "Về Gạch Coffee" -> cuộn tới khu tương ứng trên trang chủ.
export const ABOUT_SECTIONS = [
  { id: 'dia-chi', label: 'Địa chỉ quán', icon: 'bi-geo-alt' },
  { id: 'nguon-goc', label: 'Nguồn gốc', icon: 'bi-book' },
  { id: 'dich-vu', label: 'Dịch vụ', icon: 'bi-cup-hot' },
  { id: 'lien-he', label: 'Liên hệ hỗ trợ', icon: 'bi-headset' },
]
